USE [master]
GO

/****** Object:  Database [NewsPaperDB]    Script Date: 28-11-2022 13:02:13 ******/
CREATE DATABASE [NewsPaperDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewsPaperDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NewsPaperDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewsPaperDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NewsPaperDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewsPaperDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewsPaperDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewsPaperDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewsPaperDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewsPaperDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewsPaperDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewsPaperDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NewsPaperDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewsPaperDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewsPaperDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewsPaperDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewsPaperDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewsPaperDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewsPaperDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewsPaperDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewsPaperDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [NewsPaperDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewsPaperDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewsPaperDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewsPaperDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewsPaperDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewsPaperDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [NewsPaperDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewsPaperDB] SET RECOVERY FULL 
GO

ALTER DATABASE [NewsPaperDB] SET  MULTI_USER 
GO

ALTER DATABASE [NewsPaperDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewsPaperDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewsPaperDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NewsPaperDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NewsPaperDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NewsPaperDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NewsPaperDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NewsPaperDB] SET  READ_WRITE 
GO

